### ISSUE TITLE
nba: command not found

### ISSUE THREAD

**Issue by cirolin** [jaebradley/nba-cli#34]
there is something wrong. could you please give me some advice?

**Comment by jaebradley** [comment]
can you provide some more information?
- did you install the utility from `npm`?
- did you install the utility globally? (i.e. did you use the `-g` flag when installing from `npm`?)

**Comment by cirolin** [comment]
thank you!  i did not use the -g, now everything is fine but (npm WARN unmet dependency /usr/local/lib/node_modules/nba-scoreboard/node_modules/nba-images requires node-emoji@'latest' but will load), how to fix this problem?

**Comment by cirolin** [comment]
thank you! i did not use the -g, now everything is fine but (npm WARN unmet dependency /home/cirolin/node_modules/nba-scoreboard/node_modules/nba-images requires node-emoji@'latest' but will load). i installed node-emoji from npm -g, but failed to fix this problem.

**Comment by jaebradley** [comment]
can you try updating?

**Comment by cirolin** [comment]
yes, i have tried.
sudo npm update npm -g
sudo npm update node-emoji -g
sudo npm update nba-scoreboard -g

**Comment by jaebradley** [comment]
can you add a screenshot?

[This Stackoverflow article](http://stackoverflow.com/questions/20764881/why-does-npm-install-say-i-have-unmet-dependencies) might help.

**Comment by cirolin** [comment]
i read the Stackoverflow and try the way in it, but still failed...
here is the screenshot:
![nba1](https://cloud.githubusercontent.com/assets/8934922/15201915/60958a0c-1828-11e6-90d4-bbd80bf533ca.jpg)
![nba2](https://cloud.githubusercontent.com/assets/8934922/15201919/69e72f98-1828-11e6-8d89-6cd2599d37e9.jpg)

**Comment by cirolin** [comment]
now there is not WARN, but the emoji still can't show.

![nba4](https://cloud.githubusercontent.com/assets/8934922/15202325/c4e64246-182b-11e6-873f-5de17bb665c1.jpg)

**Comment by jaebradley** [comment]
could this be an issue with how your system displays emojis / unicode?

**Comment by cirolin** [comment]
Installing **ttf-ancient-fonts** from Ubuntu app store can fix this problem. Thank you for the helpful tool!
