### ISSUE TITLE
why show nothing

### ISSUE THREAD

**Issue by LingDad** [jaebradley/nba-cli#35]

**Comment by jaebradley** [comment]
If I understand you correctly, you want to know why the command `nba` shows nothing?  If so, that's a good point -- I'll output help instructions if just `nba`.

**Comment by jaebradley** [comment]
![image](https://cloud.githubusercontent.com/assets/8136030/15200987/1386778a-17ba-11e6-8400-e7e3da92ccf3.png)

**Comment by LingDad** [comment]
no, nba games today or any of the command show nothing, i am sure i installed correctly.

**Comment by jaebradley** [comment]
can you please try updating and running any of the commands and add screenshots?

**Comment by LingDad** [comment]
![screenshot from 2016-05-12 16-06-23](https://cloud.githubusercontent.com/assets/11773728/15207921/a588eb76-185b-11e6-8fe8-cde10c997c7e.png)
