### ISSUE TITLE
Timezone for games not updated

### ISSUE THREAD

**Issue by yasaswivempati** [jaebradley/nba-cli#98]
![screenshot from 2017-01-03 16 45 44](https://cloud.githubusercontent.com/assets/3521371/21628398/18b915d0-d1d4-11e6-8724-1a3f580aae0d.png)

I'm in the west coast (PST) and the games do not show in local time. See attached screenshot for details.

**Comment by jaebradley** [comment]
@yasaswivempati After you update, if you still see this issue, feel free to reopen.
